### ISSUE TITLE
code error?

### ISSUE THREAD

**Issue by kikisc123** [mc2-project/muse#1]
i do not find this:

use use io_utils::IMuxSync;

this code in muse/rust/protocols/src/test.rs,the 8th line

is there something wrong here? The error is following:
*******************************************************************
error[E0432]: unresolved import `io_utils::IMuxSync`
 --> protocols/src/tests.rs:8:5
  |
8 | use io_utils::IMuxSync;
  |     ^^^^^^^^^^^^^^^^^^ no `IMuxSync` in the root
*******************************************************************
And i build it by vscode in ubuntu .

**Comment by ryanleh** [comment]
Hi @kikisc123,

Thanks for bringing this up. It seems I forgot to update this repo for changes I made to the `io_utils` crate. I will do so in the next day or so.

**Comment by ryanleh** [comment]
Just FYI I'm a bit busier than I envisioned so it will take me until sometime next week to fix this. If you need to fix things more immediately, just take a look at the crate [here](https://github.com/ryanleh/io-utils) and it should be clear how to correct the incorrect imports.

**Comment by kikisc123** [comment]
thanks for your reply,i will try it

**Comment by ryanleh** [comment]
@kikisc123 sorry for the delay, am just now getting to this. The file `tests.rs` that you asked about is actually very much out of date and should have been disabled by default. I've removed it from the repo to avoid any future confusion.
