### ISSUE TITLE
Inquiry about code building Issue

### ISSUE THREAD

**Issue by Meteor-Sage** [mc2-project/muse#5]
I have been impressed by your work and would greatly appreciate your assistance in resolving this problem.

Specifically, I am facing an error when executing the installation Build guide. Upon running the command "cargo +nightly build --release," I encountered an error message as shown in [Image 1].
<img width="815" alt="1" src="https://github.com/mc2-project/muse/assets/86368029/9e89c9cc-ba35-4ede-8612-ebb4534412c2">
 

To provide you with more context, I am currently using Rust version [Image 2]. However, I suspect that the issue might be related to the Rust version. Therefore, I kindly request your guidance on the specific Rust version that is known to work with the code or any other potential solutions you may suggest.
<img width="305" alt="2" src="https://github.com/mc2-project/muse/assets/86368029/46e89292-37ec-4e51-a733-7159b61bbe47">

I understand that you may be busy, but I would greatly appreciate any help or insights you can provide. Thank you in advance for your time and consideration.

Looking forward to your favorable response.

**Comment by bhuvneshchaturvedi2512** [comment]
@Meteor-Sage Could you please let me know how you resolved this issue? I am also facing the same problem and cannot figure out how to fix it. Any help would be appreciated.
